Repository NVIDIA/physicsnemo, pull requests merged in 2023-09, with the labels that each got.

#140 [FEA] ARM support for Modulus Container
  CHANGELOG.md
  Dockerfile
  Makefile
  README.md
  modulus/utils/sfno/distributed/comm.py
  pyproject.toml
Labels: 2 - In Progress

#163 0.3.0 version update
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  README.md
  modulus/__init__.py
Labels: ! - Release

#164 Hot fix dockerfile deps
  Dockerfile
Labels: ! - Release

#144 update the normalization in Ahmed body datapipe
  modulus/datapipes/gnn/ahmed_body_dataset.py
Labels: 5 - Ready to Merge

#166 Integrating Sym with Core: Network Architecture Layers
  modulus/models/layers/__init__.py
  modulus/models/layers/activations.py
  modulus/models/layers/dgm_layers.py
  modulus/models/layers/fourier_layers.py
  modulus/models/layers/fully_connected_layers.py
  modulus/models/layers/siren_layers.py
  modulus/models/layers/spectral_layers.py
  test/models/test_layers_dgm.py
  test/models/test_layers_fourier.py
  test/models/test_layers_siren.py
  test/models/test_layers_spectral.py
Labels: 3 - Ready for Review

#139 [FEA] distributed gnn primitives
  CHANGELOG.md
  README.md
  modulus/distributed/__init__.py
  modulus/distributed/autograd.py
  modulus/distributed/manager.py
  modulus/distributed/utils.py
  modulus/models/gnn_layers/__init__.py
  modulus/models/gnn_layers/distributed_graph.py
  modulus/models/gnn_layers/graph.py
  modulus/models/gnn_layers/utils.py
  modulus/models/graphcast/graph_cast_net.py
  modulus/models/graphcast/graph_cast_processor.py
  modulus/models/layers/fused_silu.py
  modulus/models/meshgraphnet/meshgraphnet.py
  test/distributed/test_manager.py
  test/models/graphcast/test_graphcast.py
  test/models/graphcast/test_graphcast_snmg.py
  test/models/graphcast/utils.py
  test/models/meshgraphnet/test_meshgraphnet_snmg.py
  test/models/meshgraphnet/utils.py
  test/models/sfno/test_sfno.py
Labels: enhancement, 3 - Ready for Review, distributed

#104 SFNO refactoring - Part 1
  CHANGELOG.md
  modulus/experimental/models/sfno/__init__.py
  modulus/experimental/models/sfno/activations.py
  modulus/experimental/models/sfno/contractions.py
  modulus/experimental/models/sfno/factorizations.py
  modulus/experimental/models/sfno/layers.py
  modulus/experimental/models/sfno/preprocessor.py
  modulus/experimental/models/sfno/s2convolutions.py
  modulus/experimental/models/sfno/sfnonet.py
  modulus/experimental/utils/sfno/distributed/dist_layers.py
  modulus/models/afno/afno.py
  modulus/models/graphcast/graph_cast_net.py
  modulus/models/meta.py
  setup.py
  test/models/test_afno.py
Labels: enhancement, 3 - Ready for Review
