Repository NVIDIA/physicsnemo, pull requests merged in 2023-08, with the labels that each got.

#96 Version update 0.2.0
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  modulus/__init__.py
Labels: 3 - Ready for Review, ! - Release

#108 Hot-fix NCCL CUDA Graphs bug
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  modulus/__init__.py
  modulus/utils/capture.py
Labels: 3 - Ready for Review, ! - Hotfix, ! - Release

#103 Adding better auto labels for issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/documentation_request.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: 3 - Ready for Review

#101 Updating main to 0.3.0a0
  CHANGELOG.md
  modulus/__init__.py
Labels: 3 - Ready for Review

#90 Expanding climate datapipes to include cosin zenith, land sea mask, geopotential and latlong
  CHANGELOG.md
  modulus/experimental/__init__.py
  modulus/experimental/datapipes/__init__.py
  modulus/experimental/datapipes/climate/__init__.py
  modulus/experimental/datapipes/climate/climate_hdf5.py
  modulus/experimental/datapipes/climate/utils/__init__.py
  modulus/experimental/datapipes/climate/utils/zenith_angle.py
  test/datapipes/common/cuda_graphs.py
  test/datapipes/common/iterator_check.py
  test/datapipes/test_climate_hdf5.py
Labels: enhancement, 2 - In Progress

#111 Hot-fix security issues with certifi
  CHANGELOG.md
  pyproject.toml
Labels: ! - Hotfix, ! - Release

#129 update contribution doc and PR template
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: documentation, 3 - Ready for Review

#136 flexible processor layer size for meshgraphnet
  modulus/models/meshgraphnet/meshgraphnet.py
Labels: enhancement, 3 - Ready for Review

#105 [FEA] distributed autograd primitives (for tensors of variable size on each rank)
  CHANGELOG.md
  modulus/distributed/autograd.py
  modulus/distributed/utils.py
  test/distributed/test_autograd.py
Labels: enhancement, 5 - Ready to Merge, distributed

#149 Fixing CI image
  CHANGELOG.md
  Dockerfile
Labels: 3 - Ready for Review
