Repository NVIDIA/physicsnemo, pull requests merged in 2023-11, with the labels that each got.

#216 Adding NGC model file support to filesystem
  CHANGELOG.md
  modulus/utils/filesystem.py
  test/utils/test_filesystem.py
Labels: 4 - In Review

#157 [FEA] CRPS and EFI Update
  CHANGELOG.md
  modulus/metrics/climate/efi.py
  modulus/metrics/general/crps.py
  test/metrics/test_metrics_climate.py
  test/metrics/test_metrics_general.py
Labels: ! - Release, 4 - In Review

#181 [FEA] Improve distributed api docs
  docs/api/modulus.distributed.rst
  modulus/distributed/utils.py
Labels: documentation, ! - Release

#180 [FEA] Improve model api docs
  docs/api/modulus.models.rst
Labels: documentation, ! - Release

#226 Make changes for pydantic update
  CHANGELOG.md
  examples/cfd/ahmed_body_mgn/train.py
  examples/cfd/vortex_shedding_mgn/train.py
  examples/weather/graphcast/train_graphcast.py
  pyproject.toml
Labels: ! - Release

#222 [Docs] Migrate doc changes from launch repo
  Dockerfile
  docs/Makefile
  docs/img/FourCastNet.gif
  docs/img/ahmed_body_results.png
  docs/img/bloodflow_1d_mgn_geometries.png
  docs/img/bloodflow_1d_mgn_results.gif
  docs/img/gray_scott_predictions_blog_2.gif
  docs/img/vortex_shedding.gif
  docs/index.rst
Labels: documentation, ! - Release

#220 exclude experimental from ci
  .pre-commit-config.yaml
  pyproject.toml
  test/coverage.docstring.rc
Labels: 4 - In Review

#184 [FEA] Improve metrics api docs
  docs/api/modulus.metrics.rst
  modulus/metrics/climate/efi.py
  modulus/metrics/general/calibration.py
  modulus/metrics/general/crps.py
  modulus/metrics/general/ensemble_metrics.py
  modulus/metrics/general/entropy.py
  modulus/metrics/general/histogram.py
  modulus/metrics/general/wasserstein.py
  test/metrics/test_metrics_general.py
Labels: documentation, ! - Release

#234 SFNO update - part 2
  CHANGELOG.md
  modulus/experimental/sfno/README.md
  modulus/experimental/sfno/convert_legacy_to_flexible.py
  modulus/experimental/sfno/docker/Dockerfile
  modulus/experimental/sfno/docker/build.sh
  modulus/experimental/sfno/inference/inferencer.py
  modulus/experimental/sfno/mpu/helpers.py
  modulus/experimental/sfno/mpu/layers.py
  modulus/experimental/sfno/mpu/mappings.py
  modulus/experimental/sfno/networks/helpers.py
  modulus/experimental/sfno/perf_tests/afno/afnonetv2.py
  modulus/experimental/sfno/perf_tests/afno/block.py
  modulus/experimental/sfno/perf_tests/distributed/comm_test.py
  modulus/experimental/sfno/perf_tests/distributed/dist_fft.py
  modulus/experimental/sfno/perf_tests/distributed/dist_fft3d.py
  modulus/experimental/sfno/perf_tests/distributed/dist_ifft.py
  modulus/experimental/sfno/perf_tests/distributed/dist_ifft3d.py
  modulus/experimental/sfno/perf_tests/primitives/comp_mult.py
  modulus/experimental/sfno/perf_tests/sfno/shtfilter.py
  modulus/experimental/sfno/third_party/torch/optim/adam.py
  modulus/experimental/sfno/third_party/torch/optim/adamw.py
  modulus/experimental/sfno/train.py
  modulus/experimental/sfno/utils/comm.py
  modulus/experimental/sfno/utils/dataloader.py
  modulus/experimental/sfno/utils/dataloaders/dali_es_helper_2d.py
  modulus/experimental/sfno/utils/dataloaders/data_loader_dali_2d.py
  modulus/experimental/sfno/utils/distributed_patch.py
  modulus/experimental/sfno/utils/metric.py
  modulus/experimental/sfno/utils/trainer.py
  modulus/experimental/sfno/utils/trainer_profile.py
Labels: 2 - In Progress

#218 Denoising diffusion tutorial
  CHANGELOG.md
  docs/img/diffusion_doc/Media14.gif
  docs/img/diffusion_doc/Media7.gif
  docs/img/diffusion_doc/Picture2.png
  docs/img/diffusion_doc/backward.png
  docs/img/diffusion_doc/data_distribution.png
  docs/img/diffusion_doc/density_scaling.gif
  docs/img/diffusion_doc/diffusion_intuition.png
  docs/img/diffusion_doc/diffusion_training.png
  docs/img/diffusion_doc/discretization_error.png
  docs/img/diffusion_doc/distorted_trajectory.gif
  docs/img/diffusion_doc/edm_table.png
  docs/img/diffusion_doc/edm_table_heun.png
  docs/img/diffusion_doc/final_table.png
  docs/img/diffusion_doc/forward_diffusion.gif
  docs/img/diffusion_doc/gradual_denoising.gif
  docs/img/diffusion_doc/heun_step.png
  docs/img/diffusion_doc/loss_weighting.png
  docs/img/diffusion_doc/multiple_gradual_denoising.gif
  docs/img/diffusion_doc/noise_distribution.png
  docs/img/diffusion_doc/noise_schedule_table.png
  docs/img/diffusion_doc/ode_backward.gif
  docs/img/diffusion_doc/ode_time_step.gif
  docs/img/diffusion_doc/refine_steps.gif
  docs/img/diffusion_doc/schedule.png
  docs/img/diffusion_doc/sde.png
  docs/img/diffusion_doc/single_shot.png
  docs/img/diffusion_doc/skip_weight.png
  docs/img/diffusion_doc/table_training.png
  docs/img/diffusion_doc/time_step.png
  docs/img/diffusion_doc/time_steps_formula.png
  docs/img/diffusion_doc/variable_schedule.gif
  docs/img/diffusion_doc/variable_step_size.gif
  examples/generative/diffusion/README.md
Labels: documentation, 5 - Ready to Merge

#188 Distributed process group configuration mechanism and utility to create process groups from the `ProcessGroupConfig`
  CHANGELOG.md
  modulus/distributed/__init__.py
  modulus/distributed/config.py
  modulus/distributed/manager.py
  modulus/distributed/mappings.py
  pyproject.toml
  test/distributed/test_config.py
  test/distributed/test_manager.py
Labels: 4 - In Review, distributed

#250 ResDiff integration: switch to pip install of edm sampler
  modulus/experimental/resdiff/generate.py
Labels: 3 - Ready for Review

#247 ResDiff Integration: Switch to Modulus Distributed Util
  modulus/experimental/resdiff/fid.py
  modulus/experimental/resdiff/generate.py
  modulus/experimental/resdiff/torch_utils/distributed.py
  modulus/experimental/resdiff/train.py
  modulus/experimental/resdiff/training/dataset.py
  modulus/experimental/resdiff/training/img_utils.py
  modulus/experimental/resdiff/training/loss.py
  modulus/experimental/resdiff/training/networks.py
  modulus/experimental/resdiff/training/test_dataset.py
  modulus/experimental/resdiff/training/training_loop.py
Labels: 3 - Ready for Review

#251 ResDiff integration: Switch to Modulus Logging
  modulus/experimental/resdiff/generate.py
  modulus/experimental/resdiff/train.py
  modulus/experimental/resdiff/training/training_loop.py
Labels: 3 - Ready for Review

#257 ResDiff integration: Black formatting
  modulus/experimental/resdiff/baselines/era5.py
  modulus/experimental/resdiff/baselines/fit_rf.py
  modulus/experimental/resdiff/baselines/rf.py
  modulus/experimental/resdiff/concat.py
  modulus/experimental/resdiff/dataset_tool.py
  modulus/experimental/resdiff/dnnlib/util.py
  modulus/experimental/resdiff/docs/2023-arxiv/figures/analysis_untils.py
  modulus/experimental/resdiff/docs/2023-arxiv/figures/autocorrelation.py
  modulus/experimental/resdiff/docs/2023-arxiv/figures/benchmark.py
  modulus/experimental/resdiff/docs/2023-arxiv/figures/config.py
  modulus/experimental/resdiff/docs/2023-arxiv/figures/plot_front.py
  modulus/experimental/resdiff/docs/2023-arxiv/figures/plot_historical_typhoons.py
  modulus/experimental/resdiff/docs/2023-arxiv/figures/plot_reflectivity_maps.py
  modulus/experimental/resdiff/docs/2023-arxiv/figures/plot_spectra_logPDFs.py
  modulus/experimental/resdiff/docs/2023-arxiv/figures/plot_typhoon_analysis.py
  modulus/experimental/resdiff/docs/2023-arxiv/figures/plot_typhoon_forecast.py
  modulus/experimental/resdiff/docs/2023-arxiv/figures/scores_for_table.py
  modulus/experimental/resdiff/docs/2023-arxiv/figures/time_means.py
  modulus/experimental/resdiff/docs/2023-arxiv/generation_scripts/2023-05-31-very-out-of-sample/fcn.py
  modulus/experimental/resdiff/docs/2023-arxiv/generation_scripts/2023-05-31-very-out-of-sample/save_cwb.py
  modulus/experimental/resdiff/docs/2023-arxiv/generation_scripts/plot.py
  modulus/experimental/resdiff/docs/2023-arxiv/generation_scripts/save_cwb_2022.py
  modulus/experimental/resdiff/docs/2023-arxiv/train_and_score_baseline_models.py
  modulus/experimental/resdiff/example.py
  modulus/experimental/resdiff/fid.py
  modulus/experimental/resdiff/generate.py
  modulus/experimental/resdiff/plot_multiple_samples.py
  modulus/experimental/resdiff/plot_single_sample.py
  modulus/experimental/resdiff/power_spectra.py
  modulus/experimental/resdiff/score_samples.py
  modulus/experimental/resdiff/test_cwb_era5.py
  modulus/experimental/resdiff/torch_utils/distributed.py
  modulus/experimental/resdiff/torch_utils/misc.py
  modulus/experimental/resdiff/torch_utils/persistence.py
  modulus/experimental/resdiff/torch_utils/training_stats.py
  modulus/experimental/resdiff/train.py
  modulus/experimental/resdiff/training/YParams.py
  modulus/experimental/resdiff/training/dataset.py
  modulus/experimental/resdiff/training/dataset_old.py
  modulus/experimental/resdiff/training/img_utils.py
  modulus/experimental/resdiff/training/loss.py
  modulus/experimental/resdiff/training/networks.py
  modulus/experimental/resdiff/training/test_autoresume.py
  modulus/experimental/resdiff/training/test_parse_time.py
  modulus/experimental/resdiff/training/time.py
  modulus/experimental/resdiff/training/training_loop.py
Labels: 3 - Ready for Review
