Repository NVIDIA/physicsnemo, pull requests merged in 2023-07, with the labels that each got.

#70 Adding a CHANGELOG.md
  .gitlab/merge_request_templates/Default.md
  CHANGELOG.md
  CONTRIBUTING.md
Labels: documentation, 2 - In Progress

#71 23.08 Release preparation
  .gitmodules
  CHANGELOG.md
  Dockerfile
  modulus/models/layers/fused_silu.py
  modulus/utils/filesystem.py
  pyproject.toml
  test/deploy/test_onnx_fft.py
  test/deploy/test_onnx_utils.py
  test/models/common/inference.py
  test/utils/test_filesystem.py
Labels: 3 - Ready for Review, ! - Release

#69 remove accompanying licenses
  accompanying_licenses/all_licenses.txt
  accompanying_licenses/explanation.txt
Labels: 2 - In Progress, ! - Release

#80 fix editable install
  CHANGELOG.md
  modulus/utils/capture.py
Labels: bug, 2 - In Progress

#81 [feature] 4D version of FNO
  CHANGELOG.md
  modulus/models/fno/fno.py
  modulus/models/layers/__init__.py
  modulus/models/layers/fully_connected_layers.py
  modulus/models/layers/spectral_layers.py
  test/models/data/fno4d_output.pth
  test/models/test_fno.py
  test/models/test_nd_conv_layers.py
Labels: enhancement, 2 - In Progress

#82 Adjustments to Github Templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/documentation_request.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: enhancement, 3 - Ready for Review

#85 Enh ext sfno update
  CHANGELOG.md
  modulus/datapipes/climate/sfno/dataloader.py
  modulus/datapipes/climate/sfno/dataloaders/dali_es_helper_2d.py
  modulus/datapipes/climate/sfno/dataloaders/data_loader_dali_2d.py
  modulus/datapipes/climate/sfno/dataloaders/data_loader_dummy.py
  modulus/datapipes/climate/sfno/dataloaders/data_loader_multifiles.py
  modulus/models/sfno/activations.py
  modulus/models/sfno/contractions.py
  modulus/models/sfno/factorizations.py
  modulus/models/sfno/initialization.py
  modulus/models/sfno/layers.py
  modulus/models/sfno/preprocessor.py
  modulus/models/sfno/s2convolutions.py
  modulus/models/sfno/sfnonet.py
  modulus/utils/sfno/distributed/comm.py
  modulus/utils/sfno/distributed/helpers.py
  modulus/utils/sfno/distributed/layer_norm.py
  modulus/utils/sfno/distributed/layers.py
  modulus/utils/sfno/distributed/mappings.py
  modulus/utils/sfno/logging_utils.py
  modulus/utils/sfno/loss.py
  modulus/utils/sfno/metric.py
  modulus/utils/sfno/metrics/weighted_acc_rmse.py
  modulus/utils/sfno/warmup_scheduler.py
  modulus/utils/sfno/zenith_angle.py
  test/datapipes/sfno/test_data_loader_dummy.py
  test/models/data/sfno_output.pth
  test/models/sfno/test_sfno.py
Labels: enhancement, 3 - Ready for Review, 4 - Needs Modulus Reviewer

#84 fix: AMP in static capture
  CHANGELOG.md
  modulus/utils/capture.py
  test/utils/test_capture.py
Labels: bug, 3 - Ready for Review

#89 Update DGL install for Docker
  Dockerfile
Labels: 3 - Ready for Review, ! - Release

#91 Bug ext vortex shedding datapipe
  modulus/datapipes/gnn/__init__.py
  modulus/datapipes/gnn/vortex_shedding_dataset.py
  test/datapipes/test_ahmed_body.py
Labels: bug, 3 - Ready for Review, ! - Release
