Repository NVIDIA/physicsnemo, pull requests merged in 2023-10, with the labels that each got.

#182 Add cos_zenith_angle_from_timestamp
  modulus/datapipes/climate/sfno/dataloaders/dali_es_helper_2d.py
  modulus/models/fcn_mip_plugin.py
  modulus/utils/zenith_angle.py
  test/utils/test_zenith_angle.py
Labels: enhancement, 5 - Ready to Merge

#192 Launch core integration part1
  CHANGELOG.md
  Dockerfile
  Makefile
  modulus/launch/__init__.py
  modulus/launch/config/__init__.py
  modulus/launch/logging/__init__.py
  modulus/launch/logging/console.py
  modulus/launch/logging/launch.py
  modulus/launch/logging/mlflow.py
  modulus/launch/logging/utils.py
  modulus/launch/logging/wandb.py
  modulus/launch/utils/__init__.py
  modulus/launch/utils/checkpoint.py
  pyproject.toml
  test/utils/test_checkpoint.py
Labels: 3 - Ready for Review

#177 Integrating Sym with Core: Network Architecture Layers- Part 2
  CHANGELOG.md
  modulus/models/layers/interpolation.py
  modulus/models/pix2pix/pix2pix.py
  modulus/models/srrn/super_res_net.py
  test/models/test_interpolation.py
Labels: 3 - Ready for Review

#197 NVFuser fixes for 23.11 Modulus release
  CHANGELOG.md
  Dockerfile
  README.md
  modulus/models/gnn_layers/mesh_graph_mlp.py
  modulus/models/layers/fused_silu.py
  test/models/common/utils.py
  test/models/graphcast/test_concat_trick.py
  test/models/graphcast/test_cugraphops.py
  test/models/test_layers_activations.py
Labels: 3 - Ready for Review, 5 - Ready to Merge

#193 EDM Diffusion Models
  CHANGELOG.md
  examples/generative/diffusion/conf/config.yaml
  examples/generative/diffusion/conf/config_fid.yaml
  examples/generative/diffusion/dataset/__init__.py
  examples/generative/diffusion/dataset/dataset.py
  examples/generative/diffusion/dataset/dataset_tool.py
  examples/generative/diffusion/fid.py
  examples/generative/diffusion/generate.py
  examples/generative/diffusion/train.py
  examples/generative/diffusion/training_loop.py
  examples/generative/diffusion/training_stats.py
  examples/generative/diffusion/utils.py
  modulus/metrics/diffusion/__init__.py
  modulus/metrics/diffusion/fid.py
  modulus/metrics/diffusion/loss.py
  modulus/models/diffusion/__init__.py
  modulus/models/diffusion/dhariwal_unet.py
  modulus/models/diffusion/layers.py
  modulus/models/diffusion/preconditioning.py
  modulus/models/diffusion/song_unet.py
  modulus/models/diffusion/unet.py
  modulus/models/diffusion/utils.py
  pyproject.toml
  test/metrics/diffusion/test_fid.py
  test/metrics/diffusion/test_losses.py
  test/models/data/ddmpp_unet_output.pth
  test/models/data/dhariwal_unet_output.pth
  test/models/data/ncsnpp_unet_output.pth
  test/models/diffusion/test_dhariwal_unet.py
  test/models/diffusion/test_song_unet.py
Labels: 3 - Ready for Review
