Repository NVIDIA/physicsnemo, pull requests merged in 2023-12, with the labels that each got.

#265 Dependency cleanup
  CHANGELOG.md
  Dockerfile
  pyproject.toml
Labels: 3 - Ready for Review

#266 ResDiff integration: Add dependencies
  CHANGELOG.md
  Dockerfile
  pyproject.toml
Labels: 3 - Ready for Review

#267 Molecular Dynamics example
  CHANGELOG.md
  docs/img/lj_system_modulus_results.png
  docs/index.rst
  examples/molecular_dynamics/lennard_jones/README.md
  examples/molecular_dynamics/lennard_jones/conf/config.yaml
  examples/molecular_dynamics/lennard_jones/download_data.py
  examples/molecular_dynamics/lennard_jones/lennard_jones_system.py
  examples/molecular_dynamics/lennard_jones/utils.py
  modulus/models/gnn_layers/mesh_graph_mlp.py
  modulus/models/meshgraphnet/meshgraphnet.py
Labels: 4 - In Review

#268 ResDiff Integration: Config Management
  examples/generative/diffusion/utils.py
  modulus/experimental/resdiff/conf/config_generate.yaml
  modulus/experimental/resdiff/conf/config_train.yaml
  modulus/experimental/resdiff/generate.py
  modulus/experimental/resdiff/train.py
  modulus/experimental/resdiff/training/YParams.py
  modulus/experimental/resdiff/training/dataset.py
  modulus/experimental/resdiff/training/img_utils.py
  modulus/experimental/resdiff/training/training_loop.py
  modulus/utils/generative/__init__.py
  modulus/utils/generative/utils.py
Labels: 2 - In Progress

#273 Tkurth/extended distributed primitives
  modulus/distributed/mappings.py
  modulus/distributed/utils.py
  modulus/models/afno/distributed/afno.py
  modulus/models/afno/distributed/layers.py
Labels: 4 - In Review, distributed

#249 [FEA] add more routines to partition graph
  CHANGELOG.md
  modulus/models/gnn_layers/__init__.py
  modulus/models/gnn_layers/distributed_graph.py
  modulus/models/gnn_layers/graph.py
  test/distributed/test_config.py
  test/distributed/test_distributed_fft.py
  test/distributed/test_manager.py
  test/models/graphcast/test_graphcast_snmg.py
  test/models/meshgraphnet/test_meshgraphnet_snmg.py
  test/models/test_graph_partition.py
Labels: enhancement, 4 - In Review

#276 Physics Informed examples: Darcy Flow
  examples/cfd/darcy_physics_informed/README.md
  examples/cfd/darcy_physics_informed/conf/config.yaml
  examples/cfd/darcy_physics_informed/conf/config_pino.yaml
  examples/cfd/darcy_physics_informed/darcy_pde.py
  examples/cfd/darcy_physics_informed/darcy_physics_informed_deeponet.py
  examples/cfd/darcy_physics_informed/darcy_physics_informed_fno.py
  examples/cfd/darcy_physics_informed/download_data.py
  examples/cfd/darcy_physics_informed/ops.py
  examples/cfd/darcy_physics_informed/requirements.txt
  examples/cfd/darcy_physics_informed/utils.py
Labels: 3 - Ready for Review

#281 ResDiff integration: Enable batch size > 1 & multi-GPU for inference, sequential model loading, bug fixes, more unit tests
  examples/generative/corrdiff/conf/config_generate.yaml
  examples/generative/corrdiff/conf/config_train.yaml
  examples/generative/corrdiff/generate.py
  examples/generative/corrdiff/inference/generate.py
  examples/generative/corrdiff/inference/read_netcdf.py
  examples/generative/corrdiff/score_samples.py
  examples/generative/corrdiff/tests/test_parse_time.py
  examples/generative/corrdiff/train.py
  examples/generative/corrdiff/training/training_loop.py
  modulus/models/diffusion/preconditioning.py
  modulus/models/diffusion/unet.py
  modulus/utils/generative/__init__.py
  modulus/utils/generative/sampler.py
  modulus/utils/generative/utils.py
  test/utils/generative/test_ablation_sampler.py
  test/utils/generative/test_format_time.py
  test/utils/generative/test_parse_int_list.py
  test/utils/generative/test_parse_time.py
  test/utils/generative/test_tuple_product.py
Labels: 3 - Ready for Review
