Repository NVIDIA/physicsnemo, pull requests merged in 2024-08, with the labels that each got.

#637 Better handling of the diffusion readme
  examples/generative/README.md
  examples/generative/diffusion/README.md
  examples/generative/diffusion/docs/README.md
Labels: 4 - In Review

#640 CorrDiff: Bug fix in gradient clipping, enable validation
  examples/generative/corrdiff/conf/dataset/cwb_generate.yaml
  examples/generative/corrdiff/train.py
Labels: 3 - Ready for Review

#642 [FEA]: SDF to STL utility using Marching Cubes
  CHANGELOG.md
  Dockerfile
  modulus/__init__.py
  modulus/utils/mesh/__init__.py
  modulus/utils/mesh/generate_stl.py
  modulus/utils/sdf.py
  pyproject.toml
  test/pytest_utils.py
  test/utils/test_mesh_utils.py
  test/utils/test_sdf.py
Labels: ! - Release

#652 Fix multi-GPU test failures
  test/models/graphcast/test_graphcast_snmg.py
  test/models/meshgraphnet/test_meshgraphnet_snmg.py
Labels: ! - Release
