Repository NVIDIA/physicsnemo, pull requests merged in 2024-07, with the labels that each got.

#389 Adding Warp implementation of SDF
  CHANGELOG.md
  modulus/utils/sdf.py
  test/utils/test_sdf.py
Labels: 3 - Ready for Review, ! - Release

#547 ModAFNO for interpolation
  CHANGELOG.md
  docs/api/modulus.models.rst
  modulus/models/afno/__init__.py
  modulus/models/afno/modafno.py
  modulus/models/afno/modembed.py
  test/models/data/modafno_output.pth
  test/models/test_modafno.py
Labels: ! - Release, 4 - In Review

#577 CRPS improvements: fast and unbiased kernel implementations
  modulus/metrics/general/crps.py
  test/metrics/test_metrics_general.py
Labels: enhancement, 4 - In Review

#593 CorrDiff: CWB Dataloader cleanups
  examples/generative/corrdiff/conf/config_generate.yaml
  examples/generative/corrdiff/conf/config_generate_patch.yaml
  examples/generative/corrdiff/conf/config_train_base.yaml
  examples/generative/corrdiff/conf/references/config_data_ref.yaml
  examples/generative/corrdiff/datasets/cwb.py
  examples/generative/corrdiff/datasets/img_utils.py
  examples/generative/corrdiff/tests/_regtest_outputs/test_dataset.test_Zarr_Dataset.out
  examples/generative/corrdiff/tests/test_dataset.py
Labels: 4 - In Review

#583 [FEA] Graph Transformer Processor for GraphCast
  CHANGELOG.md
  examples/weather/graphcast/conf/config.yaml
  examples/weather/graphcast/train_graphcast.py
  modulus/models/graphcast/graph_cast_net.py
  modulus/models/graphcast/graph_cast_processor.py
  modulus/utils/graphcast/graph.py
  test/models/graphcast/test_cugraphops.py
  test/models/graphcast/test_grad_checkpointing.py
  test/models/graphcast/test_graphcast.py
  test/pytest_utils.py
Labels: 3 - Ready for Review
