Repository NVIDIA/physicsnemo, pull requests merged in 2024-02, with the labels that each got.

#330 CorrDiff integration: Adding link to the CWA dataset
  CHANGELOG.md
  examples/generative/corrdiff/README.md
Labels: 3 - Ready for Review

#314 Consistently handle `world_size==1` in the `DistributedManager`
  CHANGELOG.md
  modulus/distributed/manager.py
  modulus/metrics/general/ensemble_metrics.py
  test/distributed/test_manager.py
  test/metrics/test_metrics_general.py
Labels: 3 - Ready for Review, distributed

#340 minor graphcast fixes
  examples/weather/graphcast/constants.py
  examples/weather/graphcast/train_graphcast.py
Labels: 3 - Ready for Review

#344 README updates 02152024
  docs/index.rst
  examples/README.md
  examples/cfd/darcy_physics_informed/README.md
  examples/molecular_dynamics/lennard_jones/README.md
Labels: documentation

#346 Enable Hydra config in vortex shedding example
  examples/cfd/vortex_shedding_mgn/conf/config.yaml
  examples/cfd/vortex_shedding_mgn/constants.py
  examples/cfd/vortex_shedding_mgn/train.py
  modulus/models/meshgraphnet/meshgraphnet.py
Labels: 2 - In Progress

#318 Bug Fix for NGC filesystem
  CHANGELOG.md
  modulus/utils/filesystem.py
Labels: 3 - Ready for Review

#355 CorrDiff: Better config handling
  examples/generative/corrdiff/conf/config_train_base.yaml
  examples/generative/corrdiff/conf/config_train_diffusion.yaml
  examples/generative/corrdiff/conf/config_train_regression.yaml
  examples/generative/corrdiff/train.py
  examples/generative/corrdiff/training/training_loop.py
Labels: 3 - Ready for Review

#296 Fea argconf model instantiation
  modulus/models/module.py
  test/models/test_kwargs_model.py
Labels: bug, 4 - In Review
