Repository NVIDIA/physicsnemo, pull requests merged in 2024-06, with the labels that each got.

#496 3D UNet
  CHANGELOG.md
  modulus/models/unet/__init__.py
  modulus/models/unet/unet.py
  test/models/data/unet_output.pth
  test/models/test_unet.py
Labels: 3 - Ready for Review

#540 [Enh] [CorrDiff] Support rectangular regions in CorrDiff
  examples/generative/corrdiff/generate.py
  examples/generative/corrdiff/training/training_loop.py
  modulus/metrics/diffusion/loss.py
  modulus/models/diffusion/song_unet.py
  modulus/models/diffusion/unet.py
  test/models/diffusion/test_song_unet.py
  test/models/diffusion/test_song_unet_pos_embd.py
Labels: 5 - Ready to Merge, ! - Release

#495 Geometric Deep Learning: VTK dataloader, mesh utilities, file format converters
  modulus/datapipes/cae/__init__.py
  modulus/datapipes/cae/mesh_datapipe.py
  modulus/datapipes/cae/readers.py
  modulus/utils/mesh/__init__.py
  modulus/utils/mesh/combine_vtp_files.py
  modulus/utils/mesh/convert_file_formats.py
  test/datapipes/test_mesh_datapipe.py
  test/models/test_unet.py
  test/utils/test_mesh_utils.py
Labels: 3 - Ready for Review, ! - Release

#563 Add missing parameter to healpix convolutional layers
  modulus/models/dlwp_healpix_layers/healpix_blocks.py
Labels: 5 - Ready to Merge, ! - Release

#525 InfiniteSampler: don't pass dataset to super class
  modulus/utils/generative/utils.py
Labels: 5 - Ready to Merge, ! - Release

#546 [CorrDiff]: Only pass interface_kwargs into ResLoss constructor, but empty for EDMLossSR
  examples/generative/corrdiff/training/training_loop.py
Labels: ! - Release

#556 Add inference scripts for Ahmed body
  examples/cfd/aero_graph_net/inference_analysis/ahmed_body.ipynb
  examples/cfd/aero_graph_net/utils.py
Labels: 5 - Ready to Merge, ! - Release
