Repository NVIDIA/physicsnemo, pull requests merged in 2024-01, with the labels that each got.

#282 switch to modulus checkpointing for inference
  examples/generative/corrdiff/conf/config_generate.yaml
  examples/generative/corrdiff/generate.py
  examples/generative/corrdiff/module.py
  modulus/models/diffusion/preconditioning.py
  modulus/models/diffusion/unet.py
Labels: 3 - Ready for Review

#285 fix training bugs
  examples/generative/corrdiff/conf/config_generate.yaml
  examples/generative/corrdiff/conf/config_train.yaml
  examples/generative/corrdiff/train.py
  examples/generative/corrdiff/training/training_loop.py
Labels: 3 - Ready for Review

#243 [FEA] hook-based support for distributed but shared parameter
  CHANGELOG.md
  modulus/distributed/__init__.py
  modulus/distributed/autograd.py
  modulus/distributed/utils.py
  modulus/launch/logging/launch.py
  test/distributed/test_utils.py
  test/models/graphcast/test_graphcast_snmg.py
  test/models/meshgraphnet/test_meshgraphnet_snmg.py
Labels: ! - Release, 4 - In Review, distributed

#292 ResDiff integratin: Enable modulus checkpointing for training
  examples/generative/corrdiff/conf/config_train.yaml
  examples/generative/corrdiff/train.py
  examples/generative/corrdiff/training/training_loop.py
  modulus/metrics/diffusion/loss.py
Labels: 3 - Ready for Review

#275 Physics Informed examples: Stokes Flow
  CHANGELOG.md
  docs/img/stokes.png
  examples/cfd/stokes_mgn/README.md
  examples/cfd/stokes_mgn/constants.py
  examples/cfd/stokes_mgn/inference.py
  examples/cfd/stokes_mgn/pi_fine_tuning.py
  examples/cfd/stokes_mgn/preprosscess.py
  examples/cfd/stokes_mgn/raw_dataset/download_dataset.sh
  examples/cfd/stokes_mgn/train.py
  examples/cfd/stokes_mgn/utils.py
Labels: 3 - Ready for Review, ! - Release

#290 Fix TypeError in CorrDiff dataloader
  examples/generative/corrdiff/training/dataset.py
Labels: 3 - Ready for Review

#302 Fix pydantic issues
  examples/cfd/ahmed_body_mgn/constants.py
  examples/cfd/stokes_mgn/train.py
Labels: ! - Release

#303 Fix minor bugs in corrdiff training
  examples/generative/corrdiff/conf/config_train.yaml
  examples/generative/corrdiff/train.py
  examples/generative/corrdiff/training/training_loop.py
Labels: 3 - Ready for Review

#304 Fix bugs in examples from weather directory
  examples/weather/dlwp/train_dlwp.py
  examples/weather/graphcast/constants.py
Labels: ! - Release

#305 Corrdiff - Make IO Asynchronous with inference
  examples/generative/corrdiff/conf/config_generate.yaml
  examples/generative/corrdiff/generate.py
Labels: 3 - Ready for Review

#309 Move URL routines to examples dir
  examples/generative/diffusion/fid.py
  examples/generative/diffusion/generate.py
  examples/generative/diffusion/misc.py
  examples/generative/diffusion/training_loop.py
  modulus/utils/generative/__init__.py
  modulus/utils/generative/utils.py
Labels: 3 - Ready for Review

#316 CorrDiff integration: Support wandb logging
  examples/generative/corrdiff/conf/config_train_diffusion.yaml
  examples/generative/corrdiff/conf/config_train_regression.yaml
  examples/generative/corrdiff/train.py
  examples/generative/corrdiff/training/training_loop.py
Labels: 3 - Ready for Review

#320 CorrDiff integration: Make cftime test optional
  test/utils/generative/test_parse_time.py
Labels: 3 - Ready for Review

#323 adding citation
  CHANGELOG.md
  CITATION.cff
Labels: 3 - Ready for Review
