Repository NVIDIA/physicsnemo, pull requests merged in 2024-05, with the labels that each got.

#473 [FEA] Synthetic dataloader for weather prediction models
  CHANGELOG.md
  examples/weather/graphcast/README.md
  examples/weather/graphcast/conf/config.yaml
  examples/weather/graphcast/train_graphcast.py
  modulus/datapipes/climate/__init__.py
  modulus/datapipes/climate/synthetic.py
  test/datapipes/test_synthetic.py
Labels: 3 - Ready for Review

#334 VFGN integration
  CHANGELOG.md
  docs/img/vfgn_doc/4-parts-final.png
  docs/img/vfgn_doc/HP-MetalJet-process.png
  docs/img/vfgn_doc/busbar.gif
  docs/img/vfgn_doc/pushing-grip.gif
  docs/img/vfgn_doc/screw.gif
  docs/img/vfgn_doc/usb.gif
  examples/additive_manufacturing/sintering_physics/README.md
  examples/additive_manufacturing/sintering_physics/conf/config.yaml
  examples/additive_manufacturing/sintering_physics/data_process/acceleration_profile.py
  examples/additive_manufacturing/sintering_physics/data_process/conf/config.yaml
  examples/additive_manufacturing/sintering_physics/data_process/deform_analyze.py
  examples/additive_manufacturing/sintering_physics/data_process/out2pvtu.py
  examples/additive_manufacturing/sintering_physics/data_process/rawdata2tfrecord_large_ts.py
  examples/additive_manufacturing/sintering_physics/data_process/utils.py
  examples/additive_manufacturing/sintering_physics/graph_dataset.py
  examples/additive_manufacturing/sintering_physics/inference.py
  examples/additive_manufacturing/sintering_physics/reading_utils.py
  examples/additive_manufacturing/sintering_physics/render_rollout.py
  examples/additive_manufacturing/sintering_physics/requirements.txt
  examples/additive_manufacturing/sintering_physics/train.py
  examples/additive_manufacturing/sintering_physics/utils.py
  modulus/models/pix2pix/pix2pix.py
  modulus/models/vfgn/__init__.py
  modulus/models/vfgn/graph_network_modules.py
  test/models/data/vfgn_encoderprocess_decode_output.pth
  test/models/data/vfgn_ls_output.pth
  test/models/data/vfgn_mlp_output.pth
  test/models/data/vfgn_output.pth
  test/models/data/vfgn_simulator_output.pth
Labels: 3 - Ready for Review

#398 A pull request for adding diffusion model for fluid data super-resolution (dfsr)
  CHANGELOG.md
  examples/generative/diffusion/conf/config_dfsr_cond_generate.yaml
  examples/generative/diffusion/conf/config_dfsr_cond_train.yaml
  examples/generative/diffusion/conf/config_dfsr_generate.yaml
  examples/generative/diffusion/conf/config_dfsr_train.yaml
  examples/generative/diffusion/dataset/__init__.py
  examples/generative/diffusion/dataset/dataset.py
  examples/generative/diffusion/docs/README.md
  examples/generative/diffusion/generate_dfsr.py
  examples/generative/diffusion/train.py
  examples/generative/diffusion/training_loop.py
  modulus/metrics/diffusion/__init__.py
  modulus/metrics/diffusion/loss.py
  modulus/models/diffusion/__init__.py
  modulus/models/diffusion/preconditioning.py
  test/metrics/diffusion/test_losses.py
  test/models/diffusion/test_preconditioning.py
Labels: 3 - Ready for Review

#310 GNN encoding/transformer
  examples/cfd/vortex_shedding_mesh_reduced/README.md
  examples/cfd/vortex_shedding_mesh_reduced/constants.py
  examples/cfd/vortex_shedding_mesh_reduced/dataset/meshPosition_all.txt
  examples/cfd/vortex_shedding_mesh_reduced/dataset/meshPosition_pivotal.txt
  examples/cfd/vortex_shedding_mesh_reduced/test.py
  examples/cfd/vortex_shedding_mesh_reduced/test_sequence.py
  examples/cfd/vortex_shedding_mesh_reduced/train.py
  examples/cfd/vortex_shedding_mesh_reduced/train_sequence.py
  modulus/datapipes/gnn/vortex_shedding_re300_1000_dataset.py
  modulus/models/layers/transformer_decoder.py
  modulus/models/mesh_reduced/mesh_reduced.py
  modulus/models/mesh_reduced/temporal_model.py
Labels: 2 - In Progress

#400 add example which trains a distributed GraphCast model on shallow-water-equations data
  CHANGELOG.md
  examples/cfd/swe_distributed_gnn/README.md
  examples/cfd/swe_distributed_gnn/config_graphcast_swe.yaml
  examples/cfd/swe_distributed_gnn/figures/dist_message_passing.png
  examples/cfd/swe_distributed_gnn/figures/dist_mlp.png
  examples/cfd/swe_distributed_gnn/figures/global_vs_local_graph.png
  examples/cfd/swe_distributed_gnn/figures/memory_scaling_dim128.png
  examples/cfd/swe_distributed_gnn/figures/val_loss_latlon.png
  examples/cfd/swe_distributed_gnn/requirements.txt
  examples/cfd/swe_distributed_gnn/shallow_water_pde_dataset.py
  examples/cfd/swe_distributed_gnn/shallow_water_solver.py
  examples/cfd/swe_distributed_gnn/train.py
  modulus/distributed/autograd.py
  modulus/distributed/manager.py
  modulus/distributed/utils.py
  modulus/models/gnn_layers/distributed_graph.py
  modulus/models/gnn_layers/graph.py
  modulus/models/graphcast/graph_cast_net.py
  modulus/utils/graphcast/graph.py
  modulus/utils/graphcast/graph_utils.py
  test/distributed/test_autograd.py
  test/distributed/test_config.py
  test/distributed/test_distributed_fft.py
  test/distributed/test_manager.py
  test/distributed/test_utils.py
  test/models/graphcast/test_graphcast_snmg.py
  test/models/meshgraphnet/test_meshgraphnet_snmg.py
  test/models/test_distributed_graph.py
  test/models/test_graph_partition.py
Labels: distributed
