Repository NVIDIA/physicsnemo, pull requests merged in 2025-08, with the labels that each got.

#1039 Update header_check.py
  test/ci_tests/header_check.py
Labels: bug

#1036 MeshGraphNet Performance: Automaticaly Use transformer engine for LayerNorm.
  physicsnemo/models/gnn_layers/mesh_graph_mlp.py
  physicsnemo/models/layers/layer_norm.py
  physicsnemo/models/meshgraphnet/meshgraphkan.py
  physicsnemo/models/meshgraphnet/meshgraphnet.py
  test/distributed/distributed_utils_for_testing.py
  test/distributed/test_autograd.py
  test/distributed/test_ball_query_shard_tensor.py
  test/distributed/test_config.py
  test/distributed/test_distributed_fft.py
  test/distributed/test_manager.py
  test/distributed/test_mesh.py
  test/distributed/test_shard_tensor_function_registration.py
  test/distributed/test_shard_tensor_grad_sharding.py
  test/distributed/test_shard_tensor_initialization.py
  test/distributed/test_shard_tensor_redistribute.py
  test/distributed/test_shard_tensor_reductions.py
  test/distributed/test_utils.py
  test/models/common/optimization.py
  test/models/conftest.py
  test/models/graphcast/test_grad_checkpointing.py
  test/models/graphcast/test_graphcast.py
  test/models/meshgraphnet/test_bsms_mgn.py
  test/models/meshgraphnet/test_meshgraphkan.py
  test/models/meshgraphnet/test_meshgraphnet.py
  test/models/meshgraphnet/test_meshgraphnet_dgl2pyg.py
  test/models/test_layer_norm.py
  test/pytest_utils.py
Labels: 3 - Ready for Review, ! - Release

#1046 Hybrid MeshGraphNet
  CHANGELOG.md
  examples/structural_mechanics/deforming_plate/README.md
  examples/structural_mechanics/deforming_plate/conf/config.yaml
  examples/structural_mechanics/deforming_plate/deforming_plate_dataset.py
  examples/structural_mechanics/deforming_plate/helpers.py
  examples/structural_mechanics/deforming_plate/inference.py
  examples/structural_mechanics/deforming_plate/preprocessor.py
  examples/structural_mechanics/deforming_plate/requirements.txt
  examples/structural_mechanics/deforming_plate/train.py
  physicsnemo/datapipes/gnn/deforming_plate_dataset.py
  physicsnemo/models/gnn_layers/mesh_edge_block.py
  physicsnemo/models/gnn_layers/mesh_graph_mlp.py
  physicsnemo/models/gnn_layers/mesh_node_block.py
  physicsnemo/models/gnn_layers/utils.py
  physicsnemo/models/meshgraphnet/__init__.py
  physicsnemo/models/meshgraphnet/hybrid_meshgraphnet.py
  test/models/data/hybridmeshgraphnet_output.pth
  test/models/meshgraphnet/test_hybrid_meshgraphnet.py
Labels: ! - Release

#989 Refactor GroupNorm and log unmatched state_dict keys
  CHANGELOG.md
  physicsnemo/launch/utils/checkpoint.py
  physicsnemo/models/diffusion/__init__.py
  physicsnemo/models/diffusion/dhariwal_unet.py
  physicsnemo/models/diffusion/layers.py
  physicsnemo/models/diffusion/song_unet.py
  physicsnemo/models/module.py
  physicsnemo/models/util_compatibility.py
  test/models/common/__init__.py
  test/models/common/utils.py
  test/models/data/checkpoint_diffusion_attention_type_1.mdlus
  test/models/data/checkpoint_diffusion_attention_type_2.mdlus
  test/models/data/checkpoint_diffusion_gn_type_1-v1.0.1.mdlus
  test/models/data/checkpoint_diffusion_gn_type_2-v1.0.1.mdlus
  test/models/data/checkpoint_diffusion_gn_type_3-v1.0.1.mdlus
  test/models/data/checkpoint_diffusion_unet_block_type_1-v1.0.1.mdlus
  test/models/data/checkpoint_diffusion_unet_block_type_2-v1.0.1.mdlus
  test/models/data/checkpoint_diffusion_unet_block_type_3-v1.0.1.mdlus
  test/models/data/output_diffusion_attention_type_1.pth
  test/models/data/output_diffusion_attention_type_2.pth
  test/models/data/output_diffusion_gn_type_1-v1.0.1.pth
  test/models/data/output_diffusion_gn_type_2-v1.0.1.pth
  test/models/data/output_diffusion_gn_type_3-v1.0.1.pth
  test/models/data/output_diffusion_unet_block_type_1-v1.0.1.pth
  test/models/data/output_diffusion_unet_block_type_2-v1.0.1.pth
  test/models/data/output_diffusion_unet_block_type_3-v1.0.1.pth
  test/models/data/output_diffusion_unet_block_unetblock_type_3-v1.0.1.pth
  test/models/data/unet_block_with_attention-v1.0.1.mdlus
  test/models/diffusion/test_layers_attention.py
  test/models/diffusion/test_layers_group_norm.py
  test/models/diffusion/test_layers_unet_block.py
  test/models/diffusion/test_unet_wrappers.py
Labels: bug, 4 - In Review

#1069 Domino fixes
  CHANGELOG.md
  examples/cfd/external_aerodynamics/domino/requirements.txt
  physicsnemo/models/domino/model.py
Labels: ! - Release

#1065 Fix radius_search for domain parallelism compatibility.
  physicsnemo/distributed/shard_tensor.py
  physicsnemo/distributed/shard_utils/__init__.py
  physicsnemo/distributed/shard_utils/conv_patches.py
  physicsnemo/distributed/shard_utils/index_ops.py
  physicsnemo/distributed/shard_utils/point_cloud_ops.py
  physicsnemo/distributed/shard_utils/unary_ops.py
  test/distributed/test_ball_query_shard_tensor.py
  test/distributed/test_shard_tensor_unary_ops.py
Labels: ! - Release
