Repository NVIDIA/physicsnemo, pull requests merged in 2025-05, with the labels that each got.

#809 Various Corrdiff optimizations for drastic increase of training efficiency
  CHANGELOG.md
  examples/generative/corrdiff/conf/base/model/patched_diffusion.yaml
  examples/generative/corrdiff/conf/base/model_size/normal.yaml
  examples/generative/corrdiff/conf/config_training_hrrr_patched_diffusion_opt.yaml
  examples/generative/corrdiff/train.py
  physicsnemo/metrics/diffusion/loss.py
  physicsnemo/models/diffusion/layers.py
  physicsnemo/models/diffusion/preconditioning.py
  physicsnemo/models/diffusion/song_unet.py
  physicsnemo/models/module.py
  physicsnemo/models/util_compatibility.py
  physicsnemo/utils/patching.py
  test/metrics/diffusion/test_losses.py
  test/models/common/checkpoints.py
  test/models/diffusion/test_song_unet_agn_amp.py
  test/models/diffusion/test_song_unet_pos_embd_agn_amp.py
Labels: enhancement, 3 - Ready for Review, 5 - Merge After Dependencies, Earth-2

#868 Catch improper use of path grad acc
  examples/generative/corrdiff/train.py
Labels: 4 - In Review

#862 This commit fixes two minor bugs in the physicsnemo profiling tools
  physicsnemo/utils/profiling/line_profile.py
  physicsnemo/utils/profiling/torch.py
Labels: bug

#885 Enable saving/loading Module compiled with torch dynamo and dynamically set AMP in CorrDiff Module wrappers
  examples/generative/corrdiff/train.py
  physicsnemo/launch/utils/checkpoint.py
  physicsnemo/models/diffusion/preconditioning.py
  physicsnemo/models/diffusion/unet.py
  physicsnemo/models/module.py
  test/models/diffusion/test_preconditioning.py
  test/models/diffusion/test_unet_wrappers.py
  test/utils/test_checkpoint.py
Labels: 4 - In Review

#871 Fea backward compatability
  physicsnemo/models/diffusion/__init__.py
  physicsnemo/models/diffusion/preconditioning.py
  physicsnemo/models/diffusion/unet.py
  physicsnemo/models/module.py
  test/models/data/diffusion_unet_0.1.0.mdlus
  test/models/diffusion/test_preconditioning.py
  test/models/diffusion/test_unet_wrappers.py
Labels: ! - Release

#913 Update lead time embedding and probabilistic variables positioning in SongUNetPosEmb
  CHANGELOG.md
  physicsnemo/models/diffusion/song_unet.py
Labels: 4 - In Review

#921 Bug fix configure domino pipeline device
  examples/cfd/external_aerodynamics/domino/src/conf/config.yaml
  physicsnemo/datapipes/cae/domino_datapipe.py
  physicsnemo/datapipes/cae/domino_sharded_datapipe.py
Labels: bug, ! - Release
