Repository NVIDIA/physicsnemo, pull requests merged in 2025-07, with the labels that each got.

#992 [Minor] Profiling Cleanup
  physicsnemo/utils/profiling/line_profile.py
Labels: 3 - Ready for Review

#998 Consolidate functionality to overrides arguments in checkpoint loading
  CHANGELOG.md
  examples/weather/corrdiff/train.py
  physicsnemo/models/diffusion/preconditioning.py
  physicsnemo/models/diffusion/song_unet.py
  physicsnemo/models/diffusion/unet.py
  physicsnemo/models/diffusion/utils.py
  physicsnemo/models/module.py
  test/models/diffusion/test_preconditioning.py
  test/models/diffusion/test_unet_wrappers.py
  test/models/test_from_checkpoint.py
Labels: bug, 4 - In Review

#985 Refactor on DoMINO `utils.py` to improve code quality
  examples/cfd/external_aerodynamics/domino/requirements.txt
  examples/cfd/external_aerodynamics/domino/src/inference_on_stl.py
  examples/cfd/external_aerodynamics/domino/src/train.py
  physicsnemo/datapipes/cae/domino_datapipe.py
  physicsnemo/utils/domino/utils.py
  test/utils/test_domino_utils.py
Labels: 3 - Ready for Review

#1012 CorrDiff bugfix: Removed unnecessary check in args overriding
  physicsnemo/models/module.py
Labels: bug, 3 - Ready for Review

#1018 Update README (container version, link to curator)
  README.md
Labels: 3 - Ready for Review

#954 restructured attention into separate class and fix errors in reshaping qkv and added inference optimization and fixes
  CHANGELOG.md
  docs/api/physicsnemo.models.rst
  examples/weather/corrdiff/conf/base/generation/base_all.yaml
  examples/weather/corrdiff/generate.py
  examples/weather/corrdiff/train.py
  physicsnemo/models/diffusion/dhariwal_unet.py
  physicsnemo/models/diffusion/layers.py
  physicsnemo/models/diffusion/preconditioning.py
  physicsnemo/models/diffusion/song_unet.py
  physicsnemo/models/diffusion/unet.py
  physicsnemo/models/diffusion/utils.py
  physicsnemo/models/util_compatibility.py
  physicsnemo/utils/diffusion/stochastic_sampler.py
  physicsnemo/utils/patching.py
  test/models/diffusion/test_dhariwal_unet.py
  test/models/diffusion/test_preconditioning.py
  test/models/diffusion/test_song_unet.py
  test/models/diffusion/test_song_unet_agn_amp.py
  test/models/diffusion/test_song_unet_pos_embd.py
  test/models/diffusion/test_song_unet_pos_embd_agn_amp.py
  test/models/diffusion/test_song_unet_pos_lt_embd.py
  test/models/diffusion/test_unet_wrappers.py
  test/utils/corrdiff/test_generation_steps.py
  test/utils/data/grid_patching_2d_apply_test0.pth
  test/utils/data/grid_patching_2d_apply_test1.pth
  test/utils/data/grid_patching_2d_apply_test2.pth
  test/utils/data/grid_patching_2d_apply_test3.pth
  test/utils/data/grid_patching_2d_overlap_count_test0.pth
  test/utils/data/grid_patching_2d_overlap_count_test1.pth
  test/utils/data/grid_patching_2d_overlap_count_test2.pth
  test/utils/data/grid_patching_2d_overlap_count_test3.pth
  test/utils/generative/test_stochastic_sampler.py
  test/utils/test_patching.py
  test/utils/validate_utils.py
Labels: 4 - In Review

#982 Fix casting in SongUNetPosEmbd and shape in CorrDiff generation
  examples/weather/corrdiff/generate.py
  physicsnemo/models/diffusion/layers.py
  physicsnemo/models/diffusion/song_unet.py
  test/models/common/__init__.py
  test/models/common/fwdaccuracy.py
  test/models/common/optimization.py
  test/models/data/songunet_pos_lt_embd_pos_embed_indexing_no_patches_corrdiff.pth
  test/models/data/songunet_pos_lt_embd_pos_embed_indexing_with_patches_corrdiff.pth
  test/models/diffusion/test_song_unet_pos_lt_embd.py
  test/models/diffusion/test_song_unet_pos_lt_embd_agn_amp.py
Labels: bug, 2 - In Progress

#971 Add patch-based support for deterministic sampler
  CHANGELOG.md
  examples/weather/corrdiff/generate.py
  physicsnemo/utils/diffusion/deterministic_sampler.py
  physicsnemo/utils/diffusion/stochastic_sampler.py
  test/utils/generative/test_deterministic_sampler.py
  test/utils/generative/test_stochastic_sampler.py
Labels: enhancement, 3 - Ready for Review, Earth-2
