Repository NVIDIA/physicsnemo, pull requests merged in 2025-02, with the labels that each got.

#783 Add the Datacenter use case
  CHANGELOG.md
  docs/img/datacenter_design_cfd.gif
  docs/img/datacenter_hybrid_training.png
  examples/cfd/datacenter/README.md
  examples/cfd/datacenter/conf/config.yaml
  examples/cfd/datacenter/conf/config_inference.yaml
  examples/cfd/datacenter/conf/config_physics_informed.yaml
  examples/cfd/datacenter/inference.py
  examples/cfd/datacenter/requirements.txt
  examples/cfd/datacenter/train.py
  examples/cfd/datacenter/train_physics_informed.py
  modulus/datapipes/cae/mesh_datapipe.py
Labels: ! - Release

#769 docs: update README.md
  README.md
Labels: ! - Release

#785 Merge dlwp-healpix updates from modulus-uw
  modulus/datapipes/healpix/coupledtimeseries_dataset.py
  modulus/datapipes/healpix/couplers.py
  modulus/datapipes/healpix/data_modules.py
  modulus/datapipes/healpix/timeseries_dataset.py
  modulus/metrics/climate/healpix_loss.py
  modulus/models/dlwp_healpix/HEALPixUNet.py
  modulus/models/dlwp_healpix_layers/__init__.py
  modulus/models/dlwp_healpix_layers/healpix_blocks.py
  test/datapipes/test_healpix.py
  test/datapipes/test_healpix_couple.py
  test/metrics/test_healpix_loss.py
  test/models/data/dlwp_healpix_unet_no_decoder_no_const.pth
  test/models/dlwp_healpix/test_healpix_blocks.py
  test/models/dlwp_healpix/test_healpix_recunet_model.py
  test/models/dlwp_healpix/test_healpix_unet_model.py
Labels: ! - Release

#786 Add random walk noise and kinematic mask
  examples/cfd/lagrangian_mgn/README.md
  examples/cfd/lagrangian_mgn/conf/data/lagrangian_dataset.yaml
  examples/cfd/lagrangian_mgn/conf/experiment/goop.yaml
  examples/cfd/lagrangian_mgn/conf/experiment/sand.yaml
  examples/cfd/lagrangian_mgn/conf/experiment/water.yaml
  examples/cfd/lagrangian_mgn/conf/experiment/water_3d.yaml
  examples/cfd/lagrangian_mgn/conf/experiment/water_ramps.yaml
  examples/cfd/lagrangian_mgn/conf/loss/mseloss.yaml
  examples/cfd/lagrangian_mgn/inference.py
  examples/cfd/lagrangian_mgn/train.py
  modulus/datapipes/gnn/lagrangian_dataset.py
  test/datapipes/test_lagrangian.py
Labels: 2 - In Progress, 4 - In Review

#784 Enable Domain Parallelism with ShardTensor
  CHANGELOG.md
  docs/api/modulus.distributed.shardtensor.rst
  docs/tutorials/fsdp_and_shard_tensor.rst
  modulus/distributed/__init__.py
  modulus/distributed/_shard_redistribute.py
  modulus/distributed/_shard_tensor_spec.py
  modulus/distributed/custom_ops/__init__.py
  modulus/distributed/custom_ops/_reductions.py
  modulus/distributed/custom_ops/_tensor_ops.py
  modulus/distributed/manager.py
  modulus/distributed/shard_tensor.py
  modulus/distributed/shard_utils/__init__.py
  modulus/distributed/shard_utils/conv_patches.py
  modulus/distributed/shard_utils/halo.py
  modulus/distributed/shard_utils/natten_patches.py
  modulus/distributed/shard_utils/patch_core.py
  modulus/distributed/utils.py
  modulus/models/gnn_layers/distributed_graph.py
  pyproject.toml
  test/distributed/distributed_utils_for_testing.py
  test/distributed/test_autograd.py
  test/distributed/test_config.py
  test/distributed/test_distributed_fft.py
  test/distributed/test_manager.py
  test/distributed/test_mesh.py
  test/distributed/test_shard_tensor_grad_sharding.py
  test/distributed/test_shard_tensor_initialization.py
  test/distributed/test_shard_tensor_redistribute.py
  test/distributed/test_utils.py
Labels: ! - Release, 4 - In Review
