Repository NVIDIA/physicsnemo, pull requests merged in 2025-06, with the labels that each got.

#932 Added requirements.txt for corrdiff + fixed import paths
  examples/weather/corrdiff/datasets/cwb.py
  examples/weather/corrdiff/datasets/dataset.py
  examples/weather/corrdiff/datasets/gefs_hrrr.py
  examples/weather/corrdiff/datasets/hrrrmini.py
  examples/weather/corrdiff/generate.py
  examples/weather/corrdiff/helpers/generate_helpers.py
  examples/weather/corrdiff/helpers/train_helpers.py
  examples/weather/corrdiff/inference/plot_multiple_samples.py
  examples/weather/corrdiff/inference/plot_single_sample.py
  examples/weather/corrdiff/inference/power_spectra.py
  examples/weather/corrdiff/requirements.txt
  examples/weather/corrdiff/score_samples.py
  examples/weather/corrdiff/train.py
Labels: 3 - Ready for Review

#942 Make NVIDIA Dali optional
  CHANGELOG.md
  Dockerfile
  pyproject.toml
Labels: ! - Release

#945 Updates for Windows
  examples/cfd/darcy_fno/README.md
  examples/cfd/darcy_fno/requirements.txt
  examples/cfd/darcy_fno/train_fno_darcy.py
  physicsnemo/launch/utils/checkpoint.py
  physicsnemo/utils/filesystem.py
Labels: ! - Release

#946 Fix typos
  docs/api/physicsnemo.distributed.rst
Labels: ! - Release

#949 Adding requirements.txt for bloodflow, diffusion, and deforming plate samples
  docs/index.rst
  examples/README.md
  examples/cfd/flow_reconstruction_diffusion/README.md
  examples/cfd/flow_reconstruction_diffusion/conf/config.yaml
  examples/cfd/flow_reconstruction_diffusion/conf/config_dfsr_cond_generate.yaml
  examples/cfd/flow_reconstruction_diffusion/conf/config_dfsr_cond_train.yaml
  examples/cfd/flow_reconstruction_diffusion/conf/config_dfsr_generate.yaml
  examples/cfd/flow_reconstruction_diffusion/conf/config_dfsr_train.yaml
  examples/cfd/flow_reconstruction_diffusion/conf/config_fid.yaml
  examples/cfd/flow_reconstruction_diffusion/dataset/__init__.py
  examples/cfd/flow_reconstruction_diffusion/dataset/dataset.py
  examples/cfd/flow_reconstruction_diffusion/dataset/dataset_tool.py
  examples/cfd/flow_reconstruction_diffusion/fid.py
  examples/cfd/flow_reconstruction_diffusion/generate.py
  examples/cfd/flow_reconstruction_diffusion/generate_dfsr.py
  examples/cfd/flow_reconstruction_diffusion/misc.py
  examples/cfd/flow_reconstruction_diffusion/requirements.txt
  examples/cfd/flow_reconstruction_diffusion/train.py
  examples/cfd/flow_reconstruction_diffusion/training_loop.py
  examples/cfd/flow_reconstruction_diffusion/training_stats.py
  examples/generative/diffusion/README.md
  examples/healthcare/bloodflow_1d_mgn/README.md
  examples/healthcare/bloodflow_1d_mgn/requirements.txt
  examples/structural_mechanics/deforming_plate/README.md
  examples/structural_mechanics/deforming_plate/requirements.txt
Labels: ! - Release

#952 Tutorial on torch.compile with RAPIDS, Warp ops.
  docs/index.rst
  docs/tutorials/performance.rst
  docs/tutorials/performance_docs/torch_compile_support.rst
Labels: ! - Release

#958 Update Main README Links
  README.md
Labels: ! - Release

#956 Add tutorial on physics addition
  docs/api/physicsnemo.models.rst
  docs/index.rst
  docs/tutorials/physics_addition.rst
  docs/tutorials/simple_logging_and_checkpointing.rst
  docs/tutorials/simple_training_example.rst
Labels: ! - Release

#960 Update physicsnemo.deploy.rst
  docs/api/physicsnemo.deploy.rst
  docs/api/physicsnemo.launch.logging.rst
Labels: ! - Release

#937 CorrDiff fixes (precond., patching, & cfg parsing)
  examples/weather/corrdiff/train.py
  physicsnemo/models/diffusion/preconditioning.py
  physicsnemo/utils/patching.py
  test/utils/generative/test_stochastic_sampler.py
  test/utils/test_patching.py
Labels: 4 - In Review

#984 Patch for deprecation of generative utils
  physicsnemo/utils/generative/__init__.py
Labels: 3 - Ready for Review
